### ISSUE TITLE
error when calculate top5_acc with 2 classes

### ISSUE THREAD

**Issue by vpeopleonatank** [oke-aditya/pytorch_cnn_trainer#30]
## 🐛 Bug
**Describe the bug**
I 'm training model with 2 class. Error appears at line 61 in `pytorch_cnn_trainer/utils.py`. By default, `maxk` always equal 5 because `topk` is fixed `(1,5)` in `train_step` and `val_step` function. `output` variable shape is `32x4` so result in error `RuntimeError: invalid argument 5: k not in range for dimension`
```
     59     maxk = max(topk)
     60     batch_size = target.size(0)
     61     _, pred = output.topk(maxk, 1, True, True)
     62     pred = pred.t()
     63     correct = pred.eq(target.view(1, -1).expand_as(pred))
```
**To Reproduce**
Just train model using `engine.fit` with 2 classes

**Expected behavior**
training process works with arbitrary number of output class

**Screenshots**
![image](https://user-images.githubusercontent.com/30976876/100817657-0be34e80-347b-11eb-82bb-da0c0eaeb1a6.png)

**Desktop (please complete the following information):**
 - OS:  ubuntu 20.04

**Additional context**

**Comment by oke-aditya** [comment]
Hello @vpeopleonatank , this repository is now not actively maintained, I will transfer issue to [quickivsion](https://github.com/Quick-AI/quickvision). I think that the issue will still persist, since this entire codeebase was migrated.

**Comment by oke-aditya** [comment]
I have migrated this issue [here](https://github.com/Quick-AI/quickvision/issues/62).
Feel free to discuss there. Quickvision has exact same training recipe and is rigorously tested as well.
